cronos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(r"admin/", admin.site.urls),
    path(r"", include("oidc.urls")),

    path(r"", include("registrar.urls")),
    path(r"<int:year>/<str:season>/<str:course_number>/exams/", include("exams.urls")),
]

exams/urls.py
from django.urls import path

from . import views

app_name = "exams"

urlpatterns = [
    path(r"",
         views.course,
         name="course",
         ),
    path(r"<slug:quiz_identifier>/",
         views.quiz,
         name="quiz",
         ),
    path(r"<slug:quiz_identifier>/delete/",
         views.quiz_delete,
         name="quiz-delete",
         ),
    path(r"<slug:quiz_identifier>/edit/",
         views.quiz_edit,
         name="quiz-edit",
         ),
    path(r"<slug:quiz_identifier>/accommodations/",
         views.accommodation_summary,
         name="accommodation-summary",
         ),
    path(r"<slug:quiz_identifier>/request/<str:username>/",
         views.accommodation_request,
         name="accommodation-request",
         ),
    path(r"<slug:quiz_identifier>/request/<str:username>/attachment/<int:message_id>",
         views.attachment,
         name="attachment",
         ),
]

oidc/urls.py
from django.urls import path

from . import views

app_name = "oidc"

urlpatterns = [
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("authorize", views.authorize, name="authorize"),
]

registrar/urls.py
from django.urls import path

from . import views

app_name = "registrar"

urlpatterns = [
    path(r"",
         views.index,
         name="index",
         ),
    path(r"<int:year>/<str:season>/",
         views.term,
         name="term",
         ),
    path(r"<int:year>/<str:season>/<str:course_number>/",
         views.course,
         name="course",
         ),
    path(r"<int:year>/<str:season>/<str:course_number>/edit/",
         views.course_edit,
         name="course-edit",
         ),
    path(r"<int:year>/<str:season>/<str:course_number>/delete/",
         views.course_delete,
         name="course-delete",
         ),
]

registrar/models.py
import random
import string

from django.db import models
from django.utils.translation import gettext_lazy as _

from oidc.models import User


class TermSeason(models.TextChoices):
    Fall = "FA", _("Fall")
    WINTER = "JA", _("Winter")
    SPRING = "SP", _("Spring")
    SUMMER = "SU", _("Summer")


class Term(models.Model):
    year = models.PositiveIntegerField(help_text="The year of the term.")
    season = models.CharField(max_length=2, choices=TermSeason.choices, help_text="The season of the term.")

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["year", "season"], name="term-year-season-unique"),
        ]


def access_code_default():
    return "".join(random.choices(string.ascii_uppercase, k=6))


class Course(models.Model):
    name = models.CharField(max_length=128, help_text="The course name.")
    term = models.ForeignKey(Term, on_delete=models.PROTECT, help_text="The term.", related_name="courses")
    instructors = models.ManyToManyField(User, blank=True, related_name="courses_taught")
    students = models.ManyToManyField(User, blank=True, related_name="courses_taken")
    access_code = models.CharField(max_length=6, default=access_code_default, help_text="The joining access code.")


class CourseListing(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, help_text="The course.", related_name="listings")
    number = models.CharField(max_length=16, help_text="The number.")

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["course", "number"], name="listing-course-number-unique"),
        ]

registrar/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.db import transaction
from django.forms import inlineformset_factory
from django.utils.text import gettext_lazy as _

from .models import Course, CourseListing, Term, TermSeason, User


class ClassJoinForm(forms.Form):
    access_code = forms.CharField(label="Access code")

    def __init__(self, *args, course, **kwargs):
        super().__init__(*args, **kwargs)
        self._course = course
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    def clean_access_code(self):
        access_code = self.cleaned_data["access_code"].upper()
        if access_code != self._course.access_code:
            raise ValidationError(
                _("Incorrect access code"),
                code="incorrect_access_code",
            )
        return access_code


CourseListingFormSet = inlineformset_factory(Course, CourseListing, fields=("number",))


class CourseForm(forms.ModelForm):
    numbers = forms.CharField(max_length=128)
    year = forms.IntegerField(min_value=2000)
    season = forms.ChoiceField(choices=TermSeason.choices)
    instructor_usernames = forms.CharField()

    class Meta:
        model = Course
        fields = ["name", "numbers", "year", "season", "instructor_usernames"]

    def __init__(self, *args, user, **kwargs):
        super().__init__(*args, **kwargs)
        self._user = user
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
        if self.instance.pk is not None:
            self.fields["year"].disabled = True
            self.fields["year"].initial = self.instance.term.year
            self.fields["season"].disabled = True
            self.fields["season"].initial = self.instance.term.season
            self.fields["numbers"].initial = ", ".join(listing.number for listing in self.instance.listings.all())
            self.fields["instructor_usernames"].initial = ", ".join(instructor.preferred_username for instructor in self.instance.instructors.all())
        else:
            self.fields["instructor_usernames"].initial = user.preferred_username

    def clean_numbers(self):
        numbers = [number.strip() for number in self.cleaned_data["numbers"].split(",")]
        return numbers

    def clean_instructor_usernames(self):
        usernames = list({username.strip() for username in self.cleaned_data["instructor_usernames"].split(",")})
        for i, username in enumerate(usernames):
            try:
                user = User.objects.filter(preferred_username=username).order_by("-date_joined")[:1].get()
                usernames[i] = user.username
            except User.DoesNotExist:
                raise ValidationError(_("Unknown username."), code="unknown_username")
            else:
                usernames
        if self._user.username not in usernames:
            raise ValidationError(
                _("You cannot cause yourself to lose instructor status."),
                code="cannot_evict_self",
            )
        return usernames

    def clean(self, *args, **kwargs):
        cleaned = super().clean(*args, **kwargs)
        if CourseListing.objects.filter(course__term__year=cleaned["year"], course__term__season=cleaned["season"], number__in=cleaned["numbers"]).exclude(course=self.instance).exists():
            raise ValidationError(
                _("Course number already used."),
                code="number_in_use",
            )

    @transaction.atomic
    def save(self, commit: bool = True):
        instance = super().save(commit=False)
        instance.term, created = Term.objects.get_or_create(
            year=self.cleaned_data["year"],
            season=self.cleaned_data["season"],
        )
        if commit:
            instance.save()
            self.save_m2m()

        instance.instructors.set(
            User.objects.filter(username__in=self.cleaned_data["instructor_usernames"])
        )

        CourseListing.objects.filter(course=instance).exclude(number__in=self.cleaned_data["numbers"]).delete()
        instance.listings.set([
            CourseListing.objects.get_or_create(course=instance, number=number)[0]
            for number in self.cleaned_data["numbers"]
        ])
        return instance

registrar/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, reverse

from .forms import ClassJoinForm, CourseForm
from .models import Course, CourseListing, Term


def index(request):
    terms = Term.objects.filter(courses__isnull=False).distinct().order_by("-year", "-season")
    return render(request, "registrar/index.html", {"terms": terms})


@login_required
def term(request, *, year, season):
    term = get_object_or_404(
        Term.objects.all(),
        year=year,
        season=season,
    )
    listings = CourseListing.objects.filter(course__term=term).order_by("number")

    form = None
    initial = {
        "year": year,
        "season": season,
    }
    if request.user.courses_taught.exists():
        if request.method == "POST":
            form = CourseForm(request.POST, user=request.user, initial=initial)
            if form.is_valid():
                instance = form.save()
                return HttpResponseRedirect(reverse("registrar:course", kwargs={"year": form.cleaned_data["year"], "season": form.cleaned_data["season"], "course_number": instance.listings.first().number}))
        else:
            form = CourseForm(user=request.user, initial=initial)
    return render(request, "registrar/term.html", {"form": form, "listings": listings})


@login_required
def course(request, *, year, season, course_number):
    course = get_object_or_404(
        Course.objects.all(),
        term__year=year,
        term__season=season,
        listings__number=course_number,
    )
    is_instructor = course.instructors.filter(pk=request.user.pk).exists()
    is_student = course.students.filter(pk=request.user.pk).exists()

    form = None

    if not is_instructor and not is_student:
        if request.method == "POST":
            form = ClassJoinForm(request.POST, course=course)
            if form.is_valid():
                course.students.add(request.user)
                return HttpResponseRedirect(reverse("registrar:course", kwargs={"year": year, "season": season, "course_number": course_number}))
        else:
            form = ClassJoinForm(course=course)

    return render(request, "registrar/course.html", {"form": form, "course": course, "is_instructor": is_instructor, "is_student": is_student})


@login_required
def course_edit(request, *, year, season, course_number):
    course = get_object_or_404(
        Course.objects.all(),
        term__year=year,
        term__season=season,
        listings__number=course_number,
    )
    if not course.instructors.filter(pk=request.user.pk).exists():
        raise PermissionDenied
    if request.method == "POST":
        form = CourseForm(request.POST, user=request.user, instance=course)
        if form.is_valid():
            instance = form.save()
            return HttpResponseRedirect(reverse("registrar:course", kwargs={"year": year, "season": season, "course_number": instance.listings.first().number}))
    else:
        form = CourseForm(user=request.user, instance=course)
    return render(request, "registrar/course_edit.html", {"form": form, "course": course})


@login_required
def course_delete(request, *, year, season, course_number):
    course = get_object_or_404(
        Course.objects.all(),
        term__year=year,
        term__season=season,
        listings__number=course_number,
    )
    if not course.instructors.filter(pk=request.user.pk).exists():
        raise PermissionDenied
    if request.method == "POST":
        course.delete()
        return HttpResponseRedirect(reverse("registrar:term", kwargs={"year": year, "season": season}))
    return render(request, "registrar/course_delete.html", {"course": course})

registrar/templates/registrar/base.html
<!DOCTYPE html>
<html lang="en-US">

  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar bg-info mb-4">
      <div class="container">
        <a class="navbar-brand" href="{% url 'registrar:index' %}">Cronos</a>
        <span class="navbar-text">
          {% if user.is_authenticated %}
            <strong>{{ user.first_name }} {{ user.last_name }}</strong>
            ({{ user.preferred_username }})
          {% else %}
            Not logged in
          {% endif %}
        </span>
      </div>
    </nav>
    <div class="container mb-5">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          {% block breadcrumbs %}{% endblock %}
        </ol>
      </nav>
      {% block content %}{% endblock %}
    </div>
    <footer class="border-top text-muted text-center py-4">
      Cronos is <a href="https://github.com/j-mao/cronos">open-source</a> and available under the MIT License.
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>

</html>

registrar/templates/registrar/course.html
{% extends "registrar/base.html" %}

{% block title %}{{ request.resolver_match.kwargs.course_number }}: {{ course.name }}{% endblock %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'registrar:term' request.resolver_match.kwargs.year request.resolver_match.kwargs.season %}">
      {{ request.resolver_match.kwargs.year }} {{ request.resolver_match.kwargs.season }}
    </a>
  </li>
  <li class="breadcrumb-item active" aria-current="page">
    {{ request.resolver_match.kwargs.course_number }}: {{ course.name }}
  </li>
{% endblock %}

{% block content %}

  <dl class="row">
    <dt class="col-sm-3 col-md-2">Course title</dt>
    <dd class="col-sm-9 col-md-10">{{ course.name }}</dd>
    <dt class="col-sm-3 col-md-2">Instructors</dt>
    <dd class="col-sm-9 col-md-10">
      {% for instructor in course.instructors.all %}
        {{ instructor.first_name }} {{ instructor.last_name }}{% if not forloop.last %}, {% endif %}
      {% endfor %}
    </dd>
    {% if is_instructor %}
      <dt class="col-sm-3 col-md-2">Access code</dt>
      <dd class="col-sm-9 col-md-10">{{ course.access_code }}</dd>
    {% endif %}
  </dl>
  {% if is_instructor %}
  <div class="row mb-4">
    <div class="col offset-sm-3 offset-md-2">
      <a href="{% url 'registrar:course-edit' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number %}" class="btn btn-primary">
        Edit
      </a>
      <a href="{% url 'registrar:course-delete' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number %}" class="btn btn-danger">
        Delete
      </a>
    </div>
  </div>
  {% endif %}

  {% if is_instructor or is_student %}
    <h2>Available services</h2>
    <ul>
      <li>
        <a href="{% url 'exams:course' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number %}">
          Quizzes and accommodations
        </a>
      </li>
    </ul>
  {% endif %}
  {% if not is_instructor and not is_student %}
    <div class="card">
      <div class="card-body">
        <p class="lead">
          You have not joined this class on Cronos.
        </p>
        <form action="?" method="POST">
          {% csrf_token %}
          {{ form.non_field_errors }}
          <div class="row">
            <label for="{{ form.access_code.id_for_label }}" class="col-sm-3 col-md-2 col-form-label mb-1">
              Access code
            </label>
            <div class="col-sm-9 col-md-10 mb-3">
              {{ form.access_code }}
              {{ form.access_code.errors }}
            </div>
            <div class="col offset-sm-3 offset-md-2 mb-3">
              <button type="submit" class="btn btn-primary">Join</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  {% endif %}

{% endblock %}

registrar/templates/registrar/course_delete.html
{% extends "registrar/base.html" %}

{% block title %}Delete {{ course.name }}{% endblock %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'registrar:term' request.resolver_match.kwargs.year request.resolver_match.kwargs.season %}">
      {{ request.resolver_match.kwargs.year }} {{ request.resolver_match.kwargs.season }}
    </a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'registrar:course' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number %}">
      {{ request.resolver_match.kwargs.course_number }}
    </a>
  </li>
  <li class="breadcrumb-item active" aria-current="page">
    Delete
  </li>
{% endblock %}

{% block content %}

  <h2>You are about to delete {{ request.resolver_match.kwargs.course_number }}: {{ course.name }}.</h2>

  <form action="?" method="POST">
    {% csrf_token %}
    <p class="lead">
      Are you sure you wish to proceed?
      This action cannot be undone.
    </p>
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'registrar:course' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number %}" class="btn btn-secondary">
      Cancel
    </a>
  </form>

{% endblock %}

registrar/templates/registrar/course_edit.html
{% extends "registrar/base.html" %}

{% block title %}Edit {{ course.name }}{% endblock %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'registrar:term' request.resolver_match.kwargs.year request.resolver_match.kwargs.season %}">
      {{ request.resolver_match.kwargs.year }} {{ request.resolver_match.kwargs.season }}
    </a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'registrar:course' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number %}">
      {{ request.resolver_match.kwargs.course_number }}
    </a>
  </li>
  <li class="breadcrumb-item active" aria-current="page">
    Edit
  </li>
{% endblock %}

{% block content %}

  <form action="?" method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="row">
      <label for="{{ form.numbers.id_for_label }}" class="col-sm-4 col-md-3 col-lg-2 col-form-label mb-1">
        Course numbers
      </label>
      <div class="col-sm-8 col-md-9 col-lg-10 mb-3">
        {{ form.numbers }}
        <small class="text-muted">MIT course number, such as 6.1220. Use commas to separate multiple numbers in joint offerings.</small>
        {{ form.numbers.errors }}
      </div>
      <label for="{{ form.name.id_for_label }}" class="col-sm-4 col-md-3 col-lg-2 col-form-label mb-1">
        Course title
      </label>
      <div class="col-sm-8 col-md-9 col-lg-10 mb-3">
        {{ form.name }}
        <small class="text-muted">MIT course title, such as <em>Design and Analysis of Algorithms</em>.</small>
        {{ form.name.errors }}
      </div>
      <label for="{{ form.season.id_for_label }}" class="col-sm-4 col-md-3 col-lg-2 col-form-label mb-1">
        Term
      </label>
      <div class="col mb-3">
        {{ form.season }}
        <small class="text-muted">Season</small>
        {{ form.season.errors }}
      </div>
      <div class="col mb-3">
        {{ form.year }}
        <small class="text-muted">Year</small>
        {{ form.year.errors }}
      </div>
      <div class="col-12"></div>
      <label for="{{ form.instructor_usernames.id_for_label }}" class="col-sm-4 col-md-3 col-lg-2 col-form-label mb-1">
        Instructors
      </label>
      <div class="col-sm-8 col-md-9 col-lg-10 mb-3">
        {{ form.instructor_usernames }}
        <small class="text-muted">Comma-separated list of Kerberos usernames.</small>
        {{ form.instructor_usernames.errors }}
      </div>
      <div class="offset-sm-4 offset-md-3 offset-lg-2 mb-3">
        <button type="submit" class="btn btn-primary">Update</button>
        <a href="{% url 'registrar:course' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number %}" class="btn btn-danger">
          Cancel
        </a>
      </div>
    </div>
  </form>

{% endblock %}

registrar/templates/registrar/index.html
{% extends "registrar/base.html" %}

{% block title %}Cronos{% endblock %}

{% block content %}

  <h2>Welcome to Cronos</h2>

  <p class="lead">Select a term to begin.</p>

  <ul>
    {% for term in terms %}
      <li>
        <a href="{% url 'registrar:term' term.year term.season %}">
          {{ term.year }} {{ term.season }}
        </a>
      </li>
    {% endfor %}
  </ul>

{% endblock %}

registrar/templates/registrar/login_required.html
{% extends "registrar/base.html" %}

{% block title %}Login required{% endblock %}

{% block content %}

  <h2>Login required</h2>
  <p class="lead">
    Certificates are required to access this page.
    Please try to log in again with your certificate.
  </p>

{% endblock %}

registrar/templates/registrar/term.html
{% extends "registrar/base.html" %}

{% block title %}Courses in {{ request.resolver_match.kwargs.year }} {{ request.resolver_match.kwargs.season }}{% endblock %}

{% block breadcrumbs %}
  <li class="breadcrumb-item active" aria-current="page">
    {{ request.resolver_match.kwargs.year }} {{ request.resolver_match.kwargs.season }}
  </li>
{% endblock %}

{% block content %}

  <h2>Course listing</h2>

  <table class="table table-hover table-sm">
    <thead>
      <tr>
        <th>Number</th>
        <th>Title</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      {% for listing in listings %}
        <tr>
          <td>
            <a href="{% url 'registrar:course' request.resolver_match.kwargs.year request.resolver_match.kwargs.season listing.number %}">
              {{ listing.number }}
            </a>
          </td>
          <td>{{ listing.course.name }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan=2>
            <em>(None)</em>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% if form %}
    <div class="card">
      <div class="card-header">
        Add new course
      </div>
      <div class="card-body">
        <form action="?" method="POST">
          {% csrf_token %}
          {{ form.non_field_errors }}
          <div class="row">
            <label for="{{ form.numbers.id_for_label }}" class="col-sm-4 col-md-3 col-lg-2 col-form-label mb-1">
              Course numbers
            </label>
            <div class="col-sm-8 col-md-9 col-lg-10 mb-3">
              {{ form.numbers }}
              <small class="text-muted">MIT course number, such as 6.1220. Use commas to separate multiple numbers in joint offerings.</small>
              {{ form.numbers.errors }}
            </div>
            <label for="{{ form.name.id_for_label }}" class="col-sm-4 col-md-3 col-lg-2 col-form-label mb-1">
              Course title
            </label>
            <div class="col-sm-8 col-md-9 col-lg-10 mb-3">
              {{ form.name }}
              <small class="text-muted">MIT course title, such as <em>Design and Analysis of Algorithms</em>.</small>
              {{ form.name.errors }}
            </div>
            <label for="{{ form.season.id_for_label }}" class="col-sm-4 col-md-3 col-lg-2 col-form-label mb-1">
              Term
            </label>
            <div class="col mb-3">
              {{ form.season }}
              <small class="text-muted">Season</small>
              {{ form.season.errors }}
            </div>
            <div class="col mb-3">
              {{ form.year }}
              <small class="text-muted">Year</small>
              {{ form.year.errors }}
            </div>
            <div class="col-12"></div>
            <label for="{{ form.instructor_usernames.id_for_label }}" class="col-sm-4 col-md-3 col-lg-2 col-form-label mb-1">
              Instructors
            </label>
            <div class="col-sm-8 col-md-9 col-lg-10 mb-3">
              {{ form.instructor_usernames }}
              <small class="text-muted">Comma-separated list of Kerberos usernames.</small>
              {{ form.instructor_usernames.errors }}
            </div>
            <div class="offset-sm-4 offset-md-3 offset-lg-2 mb-3">
              <button type="submit" class="btn btn-primary">Create</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  {% endif %}

{% endblock %}