cronos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(r"admin/", admin.site.urls),
    path(r"", include("oidc.urls")),

    path(r"", include("registrar.urls")),
    path(r"<int:year>/<str:season>/<str:course_number>/exams/", include("exams.urls")),
]

exams/urls.py
from django.urls import path

from . import views

app_name = "exams"

urlpatterns = [
    path(r"",
         views.course,
         name="course",
         ),
    path(r"<slug:quiz_identifier>/",
         views.quiz,
         name="quiz",
         ),
    path(r"<slug:quiz_identifier>/delete/",
         views.quiz_delete,
         name="quiz-delete",
         ),
    path(r"<slug:quiz_identifier>/edit/",
         views.quiz_edit,
         name="quiz-edit",
         ),
    path(r"<slug:quiz_identifier>/accommodations/",
         views.accommodation_summary,
         name="accommodation-summary",
         ),
    path(r"<slug:quiz_identifier>/request/<str:username>/",
         views.accommodation_request,
         name="accommodation-request",
         ),
    path(r"<slug:quiz_identifier>/request/<str:username>/attachment/<int:message_id>",
         views.attachment,
         name="attachment",
         ),
]

oidc/urls.py
from django.urls import path

from . import views

app_name = "oidc"

urlpatterns = [
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("authorize", views.authorize, name="authorize"),
]

registrar/urls.py
from django.urls import path

from . import views

app_name = "registrar"

urlpatterns = [
    path(r"",
         views.index,
         name="index",
         ),
    path(r"<int:year>/<str:season>/",
         views.term,
         name="term",
         ),
    path(r"<int:year>/<str:season>/<str:course_number>/",
         views.course,
         name="course",
         ),
    path(r"<int:year>/<str:season>/<str:course_number>/edit/",
         views.course_edit,
         name="course-edit",
         ),
    path(r"<int:year>/<str:season>/<str:course_number>/delete/",
         views.course_delete,
         name="course-delete",
         ),
]

exams/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.text import gettext_lazy as _
from django.utils.text import slugify
from django.utils.timezone import make_aware

from oidc.models import User

from .models import Accommodation, AccommodationRequest, Message, Quiz


class QuizForm(forms.ModelForm):
    start = forms.CharField(widget=forms.TextInput(attrs={"type": "datetime-local"}))
    end = forms.CharField(widget=forms.TextInput(attrs={"type": "datetime-local"}))

    class Meta:
        model = Quiz
        fields = ["name", "start", "end"]

    def __init__(self, *args, course, **kwargs):
        super().__init__(*args, **kwargs)
        self._course = course
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    def clean(self, *args, **kwargs):
        if Quiz.objects.filter(course=self._course, identifier=slugify(self.cleaned_data["name"])).exclude(pk=self.instance.pk).exists():
            raise ValidationError(
                _("Quiz name is too similar to another quiz"),
                code="quiz_name_too_similar",
            )

    def clean_start(self):
        return make_aware(datetime.datetime.fromisoformat(self.cleaned_data["start"]))

    def clean_end(self):
        return make_aware(datetime.datetime.fromisoformat(self.cleaned_data["end"]))

    def save(self, commit: bool = True):
        instance = super().save(commit=False)
        instance.identifier = slugify(instance.name)
        instance.course = self._course
        if commit:
            instance.save()
            self.save_m2m()
        return instance


class AbstractMessageForm(forms.ModelForm):
    update_accommodation = forms.BooleanField(required=False)

    class Meta:
        model = Message
        fields = ["body", "attachment", "update_accommodation"]

    def __init__(self, *args, quiz: Quiz, student: User, author: User, **kwargs):
        super().__init__(*args, **kwargs)
        self._quiz = quiz
        self._student = student
        self._author = author
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    def save(self, commit: bool = True):
        instance = super().save(commit=False)
        instance.request, created = AccommodationRequest.objects.get_or_create(quiz=self._quiz, student=self._student)
        instance.author = self._author

        if commit:
            instance.save()
            self.save_m2m()
        return instance


class MessageNoChangeAccommodationForm(AbstractMessageForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["body"].required = True

    def clean_update_accommodation(self):
        return False


class MessageRemoveAccommodationForm(AbstractMessageForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean_update_accommodation(self):
        return True


class MessageUseExistingAccommodationForm(AbstractMessageForm):
    class Meta(AbstractMessageForm.Meta):
        fields = ["body", "attachment", "update_accommodation", "accommodation"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["accommodation"].queryset = Accommodation.objects.filter(
            quiz=self._quiz,
            accommodation_requests__isnull=False
        ).distinct()
        self.fields["accommodation"].required = True

    def clean_update_accommodation(self):
        return True


class MessageCreateNewAccommodationForm(AbstractMessageForm):
    location = forms.CharField(max_length=16)
    start = forms.CharField(widget=forms.TextInput(attrs={"type": "datetime-local"}))
    end = forms.CharField(widget=forms.TextInput(attrs={"type": "datetime-local"}))
    comments = forms.CharField(max_length=1024, required=False)

    class Meta(AbstractMessageForm.Meta):
        fields = ["body", "attachment", "update_accommodation", "location", "start", "end", "comments"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean_update_accommodation(self):
        return True

    def clean_start(self):
        return make_aware(datetime.datetime.fromisoformat(self.cleaned_data["start"]))

    def clean_end(self):
        return make_aware(datetime.datetime.fromisoformat(self.cleaned_data["end"]))

    def save(self, commit: bool = True):
        instance = super().save(commit=False)
        instance.accommodation = Accommodation.objects.create(
            quiz=self._quiz,
            location=self.cleaned_data["location"],
            start=self.cleaned_data["start"],
            end=self.cleaned_data["end"],
            comments=self.cleaned_data["comments"],
        )
        if commit:
            instance.save()
            self.save_m2m()
        return instance

exams/views.py
import os

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db.models import Exists, OuterRef, Prefetch
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.http import urlencode
from django.utils.timezone import make_naive

from oidc.models import User
from registrar.models import Course

from .forms import (MessageCreateNewAccommodationForm,
                    MessageNoChangeAccommodationForm,
                    MessageRemoveAccommodationForm,
                    MessageUseExistingAccommodationForm, QuizForm)
from .models import Accommodation, AccommodationRequest, Message, Quiz


@login_required
def course(request, *, year, season, course_number):
    course = get_object_or_404(
        Course.objects.all(),
        term__year=year,
        term__season=season,
        listings__number=course_number,
    )
    is_instructor = course.instructors.filter(pk=request.user.pk).exists()

    if is_instructor:
        if request.method == "POST":
            form = QuizForm(request.POST, course=course)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse("exams:course", kwargs={"year": year, "season": season, "course_number": course_number}))
        else:
            form = QuizForm(course=course)
    elif course.students.filter(pk=request.user.pk).exists():
        form = None
    else:
        raise PermissionDenied

    quizzes = Quiz.objects.filter(course=course).order_by("start").prefetch_related(
        Prefetch("accommodation_requests", queryset=AccommodationRequest.objects.filter(student=request.user), to_attr="my_accommodation_requests")
    )
    return render(request, "exams/course.html", {"form": form, "course": course, "quizzes": quizzes, "is_instructor": is_instructor})


@login_required
def quiz(request, *, year, season, course_number, quiz_identifier):
    course = get_object_or_404(
        Course.objects.all(),
        term__year=year,
        term__season=season,
        listings__number=course_number,
    )
    quiz = get_object_or_404(
        Quiz.objects.all(),
        course=course,
        identifier=quiz_identifier,
    )
    if course.instructors.filter(pk=request.user.pk).exists():
        pass
    elif course.students.filter(pk=request.user.pk).exists():
        return HttpResponseRedirect(reverse("exams:accommodation-request", kwargs={"year": year, "season": season, "course_number": course_number, "quiz_identifier": quiz_identifier, "username": request.user.username}))
    else:
        raise PermissionDenied

    accommodations = Accommodation.objects.filter(quiz=quiz, accommodation_requests__isnull=False).distinct()
    accommodation_requests = AccommodationRequest.objects.filter(quiz=quiz).annotate(read=Exists(request.user.read_accommodation_requests.filter(pk=OuterRef("pk")))).order_by("read", "student__last_name", "student__first_name", "student__preferred_username")
    return render(request, "exams/quiz.html", {"quiz": quiz, "accommodations": accommodations, "accommodation_requests": accommodation_requests})


@login_required
def quiz_edit(request, *, year, season, course_number, quiz_identifier):
    course = get_object_or_404(
        Course.objects.all(),
        term__year=year,
        term__season=season,
        listings__number=course_number,
    )
    quiz = get_object_or_404(
        Quiz.objects.all(),
        course=course,
        identifier=quiz_identifier,
    )
    if not course.instructors.filter(pk=request.user.pk).exists():
        raise PermissionDenied
    initial = {
        "start": make_naive(quiz.start),
        "end": make_naive(quiz.end),
    }
    if request.method == "POST":
        form = QuizForm(request.POST, course=course, instance=quiz, initial=initial)
        if form.is_valid():
            instance = form.save()
            return HttpResponseRedirect(reverse("exams:quiz", kwargs={"year": year, "season": season, "course_number": course_number, "quiz_identifier": instance.identifier}))
    else:
        form = QuizForm(course=course, instance=quiz, initial=initial)
    return render(request, "exams/quiz_edit.html", {"form": form, "quiz": quiz})


@login_required
def quiz_delete(request, *, year, season, course_number, quiz_identifier):
    course = get_object_or_404(
        Course.objects.all(),
        term__year=year,
        term__season=season,
        listings__number=course_number,
    )
    quiz = get_object_or_404(
        Quiz.objects.all(),
        course=course,
        identifier=quiz_identifier,
    )
    if not course.instructors.filter(pk=request.user.pk).exists():
        raise PermissionDenied
    if request.method == "POST":
        quiz.delete()
        return HttpResponseRedirect(reverse("exams:course", kwargs={"year": year, "season": season, "course_number": course_number}))
    return render(request, "exams/quiz_delete.html", {"quiz": quiz})


@login_required
def accommodation_summary(request, *, year, season, course_number, quiz_identifier):
    course = get_object_or_404(
        Course.objects.all(),
        term__year=year,
        term__season=season,
        listings__number=course_number,
    )
    quiz = get_object_or_404(
        Quiz.objects.all(),
        course=course,
        identifier=quiz_identifier,
    )
    if not course.instructors.filter(pk=request.user.pk).exists():
        raise PermissionDenied
    accommodation_requests = AccommodationRequest.objects.filter(quiz=quiz, accommodation__isnull=False).order_by("accommodation__location", "accommodation__start", "accommodation__end")
    return render(request, "exams/accommodations.html", {"quiz": quiz, "accommodation_requests": accommodation_requests})


@login_required
def accommodation_request(request, *, year, season, course_number, quiz_identifier, username):
    course = get_object_or_404(
        Course.objects.all(),
        term__year=year,
        term__season=season,
        listings__number=course_number,
    )
    quiz = get_object_or_404(
        Quiz.objects.all(),
        course=course,
        identifier=quiz_identifier,
    )

    is_instructor = course.instructors.filter(pk=request.user.pk).exists()
    is_student = course.students.filter(pk=request.user.pk).exists()
    if is_student and username != request.user.username:
        raise PermissionDenied

    student = get_object_or_404(
        User.objects.all(),
        username=username,
    )
    accommodation_types = {
        "accommodation-no-change": {
            "display": "No action to accommodation",
            "form_cls": MessageNoChangeAccommodationForm,
        },
        "accommodation-remove": {
            "display": "Remove any assigned accommodations",
            "form_cls": MessageRemoveAccommodationForm,
        },
        "accommodation-use-existing": {
            "display": "Assign to existing accommodation",
            "form_cls": MessageUseExistingAccommodationForm,
        },
        "accommodation-create-new": {
            "display": "Create new accommodation",
            "form_cls": MessageCreateNewAccommodationForm,
        },
    }
    if is_instructor and request.GET.get("accommodation") not in accommodation_types:
        return HttpResponseRedirect(reverse("exams:accommodation-request", kwargs={"year": year, "season": season, "course_number": course_number, "quiz_identifier": quiz_identifier, "username": username}) + "?" + urlencode({"accommodation": "accommodation-no-change"}))

    if is_instructor:
        form_cls = accommodation_types[request.GET["accommodation"]]["form_cls"]
    elif is_student:
        form_cls = MessageNoChangeAccommodationForm
    else:
        raise PermissionDenied

    try:
        accommodation_request = AccommodationRequest.objects.get(quiz=quiz, student=student)
    except AccommodationRequest.DoesNotExist:
        accommodation = None
    else:
        accommodation_request.read_by.add(request.user)
        accommodation = accommodation_request.accommodation

    initial = {
        "start": make_naive(quiz.start),
        "end": make_naive(quiz.end),
    }
    if request.method == "POST":
        form = form_cls(request.POST, request.FILES, quiz=quiz, student=student, author=request.user, initial=initial)
        if form.is_valid():
            message = form.save()
            message.send_email_notifications(request=request)
            accommodation_request = message.request
            accommodation_request.read_by.remove(*accommodation_request.read_by.exclude(pk=request.user.pk).all())
            return HttpResponseRedirect(reverse("exams:accommodation-request", kwargs={"year": year, "season": season, "course_number": course_number, "quiz_identifier": quiz_identifier, "username": username}))
    else:
        form = form_cls(quiz=quiz, student=student, author=request.user, initial=initial)

    messages = Message.objects.filter(
        request__quiz=quiz,
        request__student=student,
    ).order_by("-created")

    return render(request, "exams/request.html", {"form": form, "quiz": quiz, "student": student, "accommodation": accommodation, "messages": messages, "is_instructor": is_instructor, "accommodation_types": accommodation_types})


@login_required
def attachment(request, *, year, season, course_number, quiz_identifier, username, message_id):
    course = get_object_or_404(
        Course.objects.all(),
        term__year=year,
        term__season=season,
        listings__number=course_number,
    )
    get_object_or_404(
        Quiz.objects.all(),
        course=course,
        identifier=quiz_identifier,
    )

    is_instructor = course.instructors.filter(pk=request.user.pk).exists()
    is_student = course.students.filter(pk=request.user.pk).exists()
    if is_student and username != request.user.username:

exams/templates/exams/quiz.html
{% extends "exams/base.html" %}

{% block title %}{{ request.resolver_match.kwargs.course_number }} {{ quiz.name }}{% endblock %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'registrar:term' request.resolver_match.kwargs.year request.resolver_match.kwargs.season %}">
      {{ request.resolver_match.kwargs.year }} {{ request.resolver_match.kwargs.season }}
    </a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'registrar:course' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number %}">
      {{ request.resolver_match.kwargs.course_number }}
    </a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'exams:course' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number %}">
      Quizzes
    </a>
  </li>
  <li class="breadcrumb-item active" aria-current="page">
    {{ quiz.name }}
  </li>
{% endblock %}

{% block content %}

  <h2>Settings for {{ quiz.name }}</h2>

  <dl class="row">
    <dt class="col-sm-3 col-md-2">Name</dt>
    <dd class="col-sm-9 col-md-10">{{ quiz.name }}</dd>
    <dt class="col-sm-3 col-md-2">Start time</dt>
    <dd class="col-sm-9 col-md-10">{{ quiz.start }}</dd>
    <dt class="col-sm-3 col-md-2">End time</dt>
    <dd class="col-sm-9 col-md-10">{{ quiz.end }}</dd>
  </dl>
  <div class="row mb-4">
    <div class="col offset-sm-3 offset-md-2">
      <a href="{% url 'exams:quiz-edit' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number request.resolver_match.kwargs.quiz_identifier %}" class="btn btn-primary">
        Edit
      </a>
      <a href="{% url 'exams:accommodation-summary' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number request.resolver_match.kwargs.quiz_identifier %}" class="btn btn-success">
        Accommodations
      </a>
      <a href="{% url 'exams:quiz-delete' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number request.resolver_match.kwargs.quiz_identifier %}" class="btn btn-danger">
        Delete
      </a>
    </div>
  </div>

  <h2>Accommodations for {{ quiz.name }}</h2>

  <p class="lead">
    You currently have the following accommodations arrangements.
  </p>

  <table class="table table-hover table-sm">
    <thead>
      <tr>
        <th>Location</th>
        <th>Start</th>
        <th>End</th>
        <th>Comments</th>
        <th># students</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      {% for accommodation in accommodations %}
        <tr>
          <td>{{ accommodation.location }}</td>
          <td>{{ accommodation.start }}</td>
          <td>{{ accommodation.end }}</td>
          <td>{{ accommodation.comments }}</td>
          <td>{{ accommodation.accommodation_requests.count }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan=5>
            <em>(None)</em>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <p class="lead">
  Below is your inbox of accommodations requests.
  </p>

  <div class="table-responsive-sm">
    <table class="table table-hover table-sm">
      <thead>
        <tr>
          <th>Student</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Accommodation</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for accommodation_request in accommodation_requests %}
          <tr>
            <td>
              <a href="{% url 'exams:accommodation-request' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number request.resolver_match.kwargs.quiz_identifier accommodation_request.student.username %}">{{ accommodation_request.student.preferred_username }}</a>
              {% if not accommodation_request.read %}
                <span class="badge text-bg-danger">Updated</span>
              {% endif %}
            </td>
            <td>{{ accommodation_request.student.first_name }}</td>
            <td>{{ accommodation_request.student.last_name }}</td>
            <td>{{ accommodation_request.accommodation }}</td>
          </tr>
        {% empty %}
          <tr>
            <td colspan=4>
              <em>(None)</em>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock %}

exams/templates/exams/request.html
{% extends "exams/base.html" %}

{% block title %}{{ request.resolver_match.kwargs.course_number }} {{ quiz.name }}{% endblock %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'registrar:term' request.resolver_match.kwargs.year request.resolver_match.kwargs.season %}">
      {{ request.resolver_match.kwargs.year }} {{ request.resolver_match.kwargs.season }}
    </a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'registrar:course' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number %}">
      {{ request.resolver_match.kwargs.course_number }}
    </a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'exams:course' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number %}">
      Quizzes
    </a>
  </li>
  {% if is_instructor %}
    <li class="breadcrumb-item">
      <a href="{% url 'exams:quiz' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number request.resolver_match.kwargs.quiz_identifier %}">
        {{ quiz.name }}
      </a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
      Request from {{ student.preferred_username }}
    </li>
  {% else %}
    <li class="breadcrumb-item active" aria-current="page">
      {{ quiz.name }}
    </li>
  {% endif %}
{% endblock %}

{% block content %}

  <h2>
    Accommodation request for
    {{ student.first_name }} {{ student.last_name }}
    ({{ student.preferred_username }})
    on
    {{ quiz.name }}
  </h2>

  {% if accommodation %}
    <div class="alert alert-success" role="alert">
      <strong>Accommodation assigned:</strong>
      {{ accommodation }}
    </div>
  {% else %}
    <div class="alert alert-primary" role="alert">
      No accommodation assigned.
    </div>
  {% endif %}

  <div class="card mb-3">
    <div class="card-header">
      New message
    </div>
    <div class="card-body">
      <form action="?accommodation={{ request.GET.accommodation|urlencode }}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% if is_instructor %}
          <div class="row">
            <div class="col-sm-4 col-md-3 col-lg-2 mb-1">
              Accommodation
              <p class="text-muted">
                <small>
                  Please select an option before writing a message.
                </small>
              </p>
            </div>
            <div class="col mb-3">
              {% for value, spec in accommodation_types.items %}
                <div class="form-check">
                  <input
                      type="radio"
                      id="{{ value }}"
                      name="accommodation-type"
                      class="form-check-input"
                      {% if request.GET.accommodation == value %}
                        checked
                      {% else %}
                        onclick="window.location = '?accommodation={{ value|urlencode }}'; return false;"
                      {% endif %}
                  >
                  <label class="form-check-label" for="{{ value }}">{{ spec.display }}</label>
                </div>
              {% endfor %}
            </div>
          </div>
          <div class="row">
            {% if request.GET.accommodation == "accommodation-use-existing" %}
              <div class="col-sm-4 col-md-3 col-lg-2 mb-1">
                Choose accommodation
              </div>
              <div class="col mb-3">
                {{ form.accommodation }}
                {{ form.accommodation.errors }}
              </div>
            {% endif %}
            {% if request.GET.accommodation == "accommodation-create-new" %}
              <label for="{{ form.location.id_for_label }}" class="col-sm-4 col-md-3 col-lg-2 col-form-label mb-1">
                Location
              </label>
              <div class="col-sm-8 col-md-9 col-lg-10 mb-3">
                {{ form.location }}
                <small class="text-muted">Room number. For example, 32-155.</small>
                {{ form.location.errors }}
              </div>
              <label for="{{ form.start.id_for_label }}" class="col-sm-4 col-md-3 col-lg-2 col-form-label mb-1">
                Start time
              </label>
              <div class="col-sm-8 col-md-9 col-lg-10 mb-3">
                {{ form.start }}
                {{ form.start.errors }}
              </div>
              <label for="{{ form.end.id_for_label }}" class="col-sm-4 col-md-3 col-lg-2 col-form-label mb-1">
                End time
              </label>
              <div class="col-sm-8 col-md-9 col-lg-10 mb-3">
                {{ form.end }}
                {{ form.end.errors }}
              </div>
              <label for="{{ form.comments.id_for_label }}" class="col-sm-4 col-md-3 col-lg-2 col-form-label mb-1">
                Special comments
              </label>
              <div class="col-sm-8 col-md-9 col-lg-10 mb-3">
                {{ form.comments }}
                <small class="text-muted">
                  Special comments for the proctor, if any.
                  The student can also see these notes.
                </small>
                {{ form.comments.errors }}
              </div>
            {% endif %}
          </div>
        {% endif %}
        <div class="row">
          <label for="{{ form.body.id_for_label }}" class="col-sm-4 col-md-3 col-lg-2 col-form-label mb-1">
            Message
          </label>
          <div class="col-sm-8 col-md-9 col-lg-10 mb-3">
            {{ form.body }}
            {{ form.body.errors }}
          </div>
          <label for="{{ form.body.id_for_label }}" class="col-sm-4 col-md-3 col-lg-2 col-form-label mb-1">
            Attachment
          </label>
          <div class="col-sm-8 col-md-9 col-lg-10 mb-3">
            {{ form.attachment }}
            <small class="text-muted">
              If helpful, you can attach any documentation here.
            </small>
            {{ form.attachment.errors }}
          </div>
        </div>
        <div class="row">
          <div class="col offset-sm-4 offset-md-3 offset-lg-2 mb-3">
            <p class="text-muted">
              {% if is_instructor %}
                By clicking Send, the student will receive an email notifying them of your message.
              {% else %}
                By clicking Send, the course instructors will receive an email notifying them of your message.
              {% endif %}
            </p>
            <button type="submit" class="btn btn-primary">Send</button>
          </div>
        </div>
      </form>
    </div>
  </div>

  {% for message in messages %}
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title">
          {{ message.created }}
        </h5>
        <h6 class="card-subtitle mb-2 text-muted">
          {{ message.author.first_name }} {{ message.author.last_name }}
          <small>
            {% if message.update_accommodation and message.accommodation %}
              <span class="text-success">
                assigned accommodation:
                <span class="fw-light">{{ message.accommodation }}</span>
              </span>
            {% elif message.update_accommodation %}
              <span class="text-danger">
                canceled accomodations.
              </p>
            {% else %}
              said:
            {% endif %}
          </small>
        </h6>
        <p class="card-text">
          {{ message.body|linebreaks }}
        </p>
        {% if message.attachment %}
          <p class="card-text">
            <a href="{% url 'exams:attachment' request.resolver_match.kwargs.year request.resolver_match.kwargs.season request.resolver_match.kwargs.course_number request.resolver_match.kwargs.quiz_identifier request.resolver_match.kwargs.username message.pk %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-paperclip" viewBox="0 0 16 16">
                <path d="M4.5 3a2.5 2.5 0 0 1 5 0v9a1.5 1.5 0 0 1-3 0V5a.5.5 0 0 1 1 0v7a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 0-3 0v9a2.5 2.5 0 0 0 5 0V5a.5.5 0 0 1 1 0v7a3.5 3.5 0 1 1-7 0V3z"/>
              </svg>
              {{ message.attachment_filename }}
            </a>
          </p>
        {% endif %}
      </div>
    </div>
  {% endfor %}

{% endblock %}